### ISSUE TITLE
你们都怎么签名的啊？为啥我的用了几天就掉签

### ISSUE THREAD

**Issue by yy306525121** [DKJone/DKWechatHelper#101]
有没有什么便宜稳定的签名方式

**Comment by DKJone** [comment]
申请免费个人开发者，7天会掉签,推荐[AltStore](https://github.com/rileytestut/AltStore)可以自动续签，
不想费事可以99刀注册个人开发者，有效期一年

**Comment by cy920820** [comment]
收费：蒲公英用企业签、超级签、或者注册官方个人开发者账号
再亦或者直接用免费 7 天签，Cydia Impactor 、AltStore等等。

**Comment by cy920820** [comment]
> 申请免费个人开发者，7天会掉签,推荐[AltStore](https://altstore.io/)可以自动续签， 不想费事可以99刀注册个人开发者，有效期一年

续签不需要越狱吗？我之前试过没搞定

**Comment by yy306525121** [comment]
好的谢谢各位

**Comment by DKJone** [comment]
@cy920820  

不需要越狱，AltStore打开[后台刷新](https://faq.altstore.io/how-to-use-altstore/your-altstore) ,和[altserver](https://faq.altstore.io/how-to-use-altstore/altserver)在一个局域网就会自动刷新

**Comment by cy920820** [comment]
> @cy920820
> 
> 不需要越狱，AltStore打开[后台刷新](https://faq.altstore.io/how-to-use-altstore/your-altstore) ,和[altserver](https://faq.altstore.io/how-to-use-altstore/altserver)在一个局域网就会自动刷新

thx.
