### ISSUE TITLE
项目里找不到info.plist

### ISSUE THREAD

**Issue by yangsunyue** [DKJone/DKWechatHelper#107]
error: Build input file cannot be found: '/Users/ysy/Downloads/DKWechatHelper-master/dkhelper/dkhelper/Info.plist' (in target 'dkhelper' from project 'dkhelper')

**Comment by DKJone** [comment]
把xcode里的引用删掉重新编译，或者直接从安装包里复制info.plist到这个地址

**Comment by Gerry1218** [comment]
1. Build Settings -> Info.plist File 删掉
2. Generate Info.plist File 设为 YES
