### ISSUE TITLE
IOS16 闪退原因是反反调试 已解决，防撤回仍然有效，已更新8.0.29

### ISSUE THREAD

**Issue by shenzudan** [DKJone/DKWechatHelper#117]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/17032816/190162173-38012601-47e7-4f13-be7e-12081cf926dc.png">

**Comment by shenzudan** [comment]
我看闪退不知道是不是微信改了函数签名啥的，就准备自己dump下，直接就挂在第一步了。。

**Comment by shenzudan** [comment]
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/17032816/190164703-8c86f831-b491-4c02-8055-7dfa2cc5f6f4.png">
闪退原因吧

**Comment by shenzudan** [comment]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/17032816/190167884-3f3d907a-33f1-4fe2-aab2-e4819148f6c5.png">
挂的原因应该是因为这个反调试，我注释掉了
微信是会检测自己注入的动态库吗？ 那感觉还是不能用啊  一会微信搞封了
我看这玩意是AloneMonkey，都断更多久了。。难顶了，。

**Comment by shenzudan** [comment]
查了下相关文档，这个应该跟编译直接使用没关系，管它直接上了
![image](https://user-images.githubusercontent.com/17032816/190169943-b1bd01b5-4ba0-4718-82dd-fe99090f565d.png)

**Comment by shenzudan** [comment]
![image](https://user-images.githubusercontent.com/17032816/190170593-84a6fafc-a832-4b42-a622-7afd1feed091.png)
开心 可以了 其他功能就不关心了

**Comment by ed1s0ng** [comment]
请问有新版可用的安装包吗，ios16老版本闪退

**Comment by TSiGua** [comment]
请问这个需要怎么弄？

**Comment by gdunser** [comment]
我有一个正常版本，没有防撤回抢红包之类的功能

**Comment by shenzudan** [comment]
链接: https://pan.baidu.com/s/1V5bjWAEco3oPtGGvNeRGzg 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by shenzudan** [comment]
直接注入dylib会导致挂掉是因为antidebug这个里面要覆盖的函数在IOS16已经去掉了，所以程序异常挂了
我把这段代码去掉了 编译注入了8.0.28,可以正常使用，地址上面自取

**Comment by 276585877** [comment]
> 链接: https://pan.baidu.com/s/1V5bjWAEco3oPtGGvNeRGzg 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦
只有一个功能么，其他功能还生效么

**Comment by zwjtano** [comment]
请问这个文件需要怎么用？没见过的。谢谢

**Comment by shenzudan** [comment]
> > 链接: https://pan.baidu.com/s/1V5bjWAEco3oPtGGvNeRGzg 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 大佬方便传[123云盘](https://www.123pan.com/)或[阿里云盘](https://www.aliyundrive.com/)吗，百度盘没有会员好慢..

https://www.123pan.com/s/C5e0Vv-7bkw3提取码:8888  阿里云不允许这类文件分享。

**Comment by shenzudan** [comment]
> > 链接: https://pan.baidu.com/s/1V5bjWAEco3oPtGGvNeRGzg 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦
> > 只有一个功能么，其他功能还生效么

没试，你自己试试吧，我就用一个撤回和callkit

**Comment by shenzudan** [comment]
> 请问这个文件需要怎么用？没见过的。谢谢

dylib已经打进去了，直接签名可装

**Comment by KEJIXIAOYU** [comment]
> > 文件需要怎么用？没见过的。谢谢请
> 
> dylib已经打进去了，直接签名可装

可以提供ipa的文件吗？这个文件不会装。谢谢

**Comment by 276585877** [comment]
> 直接注入dylib会导致挂掉是因为antidebug这个里面要覆盖的函数在IOS16已经去掉了，所以程序异常挂了 我把这段代码去掉了 编译注入了8.0.28,可以正常使用，地址上面自取

去掉了不需要的反调试，会不会有其他检测封号的地方呢

**Comment by gdunser** [comment]
> > 我有一个正常版本，没有防撤回抢红包之类的功能
> 
> 能和appStore下的共存吗，求分享一下ipa

可以

**Comment by sigmalumia1** [comment]
改了后缀，用Appstore安装提示：The name for this app is invalid.  请教大神如何解决？

**Comment by LINECAT** [comment]
> > 请问这个文件需要怎么用？没见过的。谢谢
> 
> dylib已经打进去了，直接签名可装

大神，求直接打包的IPA

**Comment by shenzudan** [comment]
统一回复下，这个是Payload文件 直接拖到签名工具里打包,我用的IOS App Signer.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/17032816/191162863-fb4bce15-0679-489b-990a-4600127d3379.png">

**Comment by shenzudan** [comment]
> > 直接注入dylib会导致挂掉是因为antidebug这个里面要覆盖的函数在IOS16已经去掉了，所以程序异常挂了 我把这段代码去掉了 编译注入了8.0.28,可以正常使用，地址上面自取
> 
> 去掉了不需要的反调试，会不会有其他检测封号的地方呢

这个反反调试是程序debug用的，装到手机里不需要 不是防微信检测的。

**Comment by shenzudan** [comment]
https://www.123pan.com/s/C5e0Vv-dZkw3提取码:8888  
这个是ipa，你们自己重新签名吧

**Comment by oschanger** [comment]
iphone14  iOS 16.0实测，还需要在dkhelperDylib.m里加一个hook才能起
@class NetworkProcessProxy;
CHDeclareClass(NetworkProcessProxy);
CHMethod0(void, NetworkProcessProxy, addBackgroundStateObservers)
{
    return;
}


CHLoadLateClass(NetworkProcessProxy);
CHHook0(NetworkProcessProxy, addBackgroundStateObservers);

**Comment by shenzudan** [comment]
> 

是跟14有关吗，我 也是ios 16没改动原版代码哎

**Comment by shenzudan** [comment]
> iphone14 iOS 16.0实测，还需要在dkhelperDylib.m里加一个hook才能起 @Class NetworkProcessProxy; CHDeclareClass(NetworkProcessProxy); CHMethod0(void, NetworkProcessProxy, addBackgroundStateObservers) { return; }
> 
> CHLoadLateClass(NetworkProcessProxy); CHHook0(NetworkProcessProxy, addBackgroundStateObservers);

是跟14有关吗，我 也是ios 16没改动原版代码哎

**Comment by sigmalumia1** [comment]
> [https://www.123pan.com/s/C5e0Vv-dZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-dZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888) 这个是ipa，你们自己重新签名吧

请教大神，用您给的这个ipa导入到altstore安装是报错，The name for this app is invalid. ，请问怎么可以解决这个问题？谢谢

**Comment by sigmalumia1** [comment]
> > [https://www.123pan.com/s/C5e0Vv-dZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-dZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888) 这个是ipa，你们自己重新签名吧
> 
> 请教大神，用您给的这个ipa导入到altstore安装是报错，The name for this app is invalid. ，请问怎么可以解决这个问题？谢谢

https://github.com/rileytestut/AltStore/issues/310

已通过以上链接教程解决了报错的问题，供有同样问题的机油学习，再次感谢大神提供IPA文件，谢谢！

**Comment by daqueque** [comment]
> 给的这个ipa导入到altstore



> [https://www.123pan.com/s/C5e0Vv-dZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-dZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888) 这个是ipa，你们自己重新签名吧

大佬，链接失效了。

**Comment by shenzudan** [comment]
> > 给的这个ipa导入到altstore
> 
> > [https://www.123pan.com/s/C5e0Vv-dZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-dZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888) 这个是ipa，你们自己重新签名吧
> 
> 大佬，链接失效了。

晚上我更新下8.0.29的微信，别急哈

**Comment by shenzudan** [comment]
123盘会被禁止分享，你们有需要的给我发邮件吧 admin@stanwind.com
原版8.0.29微信: https://www.123pan.com/s/C5e0Vv-SZkw3提取码:8888  
打了dylib的稍后我传下

**Comment by shenzudan** [comment]
百度云文件夹: 链接: https://pan.baidu.com/s/1ibcpFtq1rM75vzNSgQdvzQ?pwd=8888 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦(dk_8.0.29是打过dylib的)
123盘: https://www.123pan.com/s/C5e0Vv-lZkw3提取码:8888

**Comment by shenzudan** [comment]
123盘会被禁止分享，你们有需要的给我发邮件吧 [admin@stanwind.com](mailto:admin@stanwind.com)
原版8.0.29微信: [https://www.123pan.com/s/C5e0Vv-SZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-SZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)

百度云文件夹:链接: https://pan.baidu.com/s/1T48cbq-UDqyn7YkoHbCvCg?pwd=8888 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦(dk_8.0.29是打过dylib的)
123盘:https://www.123pan.com/s/C5e0Vv-7Zkw3提取码:8888

**Comment by shenzudan** [comment]
![image](https://user-images.githubusercontent.com/17032816/192299013-a73eb75e-74d6-4d69-ab22-7671a2413e77.png)

**Comment by cy920820** [comment]
> 123盘会被禁止分享，你们有需要的给我发邮件吧 [admin@stanwind.com](mailto:admin@stanwind.com) 原版8.0.29微信: [https://www.123pan.com/s/C5e0Vv-SZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-SZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)
> 
> 百度云文件夹:链接: https://pan.baidu.com/s/1T48cbq-UDqyn7YkoHbCvCg?pwd=8888 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦(dk_8.0.29是打过dylib的) 123盘:[https://www.123pan.com/s/C5e0Vv-7Zkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-7Zkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)

大佬，有两个问题想问一下，请不吝赐教：
1. 请问如何自动续签，我使用 `AltStore` 签名，但是并没有实现自动续签，在网上找到的方案都是连接同一局域网下就可以实现续签，但是我并没有实现
2. 如何将原本和当前微信的聊天记录共享数据啊？或者同步数据 @shenzudan

**Comment by daqueque** [comment]
> > 123盘会被禁止分享，你们有需要的给我发邮件吧 [admin@stanwind.com](mailto:admin@stanwind.com) 原版8.0.29微信: [https://www.123pan.com/s/C5e0Vv-SZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-SZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)
> > 百度云文件夹:链接: https://pan.baidu.com/s/1T48cbq-UDqyn7YkoHbCvCg?pwd=8888 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦(dk_8.0.29是打过dylib的) 123盘:[https://www.123pan.com/s/C5e0Vv-7Zkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-7Zkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)
> 
> 大佬，有两个问题想问一下，请不吝赐教：
> 
> 1. 请问如何自动续签，我使用 `AltStore` 签名，但是并没有实现自动续签，在网上找到的方案都是连接同一局域网下就可以实现续签，但是我并没有实现
> 2. 如何将原本和当前微信的聊天记录共享数据啊？或者同步数据 @shenzudan

AltStore可以续签，亲测有效。

**Comment by daqueque** [comment]
> admin@stanwind.com

谢谢

**Comment by shenzudan** [comment]
> 

1. 续签我也不知道怎么搞哎，我看楼上有人解决了的一次只签7天的问题，我是自己开发者账号，没这个问题
2. 每次重装都会覆盖原本数据，这个我也不知道为啥，蹲一个IOS开发来解答下

**Comment by shenzudan** [comment]
> > 123盘会被禁止分享，你们有需要的给我发邮件吧 [admin@stanwind.com](mailto:admin@stanwind.com) 原版8.0.29微信: [https://www.123pan.com/s/C5e0Vv-SZkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-SZkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)
> > 百度云文件夹:链接: https://pan.baidu.com/s/1T48cbq-UDqyn7YkoHbCvCg?pwd=8888 提取码: 8888 复制这段内容后打开百度网盘手机App，操作更方便哦(dk_8.0.29是打过dylib的) 123盘:[https://www.123pan.com/s/C5e0Vv-7Zkw3提取码:8888](https://www.123pan.com/s/C5e0Vv-7Zkw3%E6%8F%90%E5%8F%96%E7%A0%81:8888)
> 
> 大佬，有两个问题想问一下，请不吝赐教：
> 
> 1. 请问如何自动续签，我使用 `AltStore` 签名，但是并没有实现自动续签，在网上找到的方案都是连接同一局域网下就可以实现续签，但是我并没有实现
> 2. 如何将原本和当前微信的聊天记录共享数据啊？或者同步数据 @shenzudan

1. 我是自己开发者账号，不知道怎么续签。。altStore确实没用过，我看楼上有七天的爱思签名如何解决的。
2. 我安装每次 也会覆盖，蹲一个ios开发来解答下吧。。

**Comment by shenzudan** [comment]
谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing
dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing

**Comment by daqueque** [comment]
> 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing

altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？

**Comment by shenzudan** [comment]
> > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> 
> altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？

https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing
试试这个，我改了包名重签的，在ipad上装了可以

**Comment by daqueque** [comment]
> > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > 
> > 
> > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> 
> https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以

谢谢

**Comment by daqueque** [comment]
> > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > 
> > 
> > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> 
> https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以

大佬，有没有简单的原版脱壳办法了？自己想脱壳。就不用麻烦别人了。

**Comment by zwjtano** [comment]
> > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > 
> > 
> > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> 
> https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以

这个可以直接用altstore安装的吗，谢谢

**Comment by 276585877** [comment]
微信步数修改无效

**Comment by shenzudan** [comment]
> > > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > > 
> > > 
> > > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> > 
> > 
> > https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以
> 
> 大佬，有没有简单的原版脱壳办法了？自己想脱壳。就不用麻烦别人了。

装crackerXI+，要越狱，我手边没越狱设备，之前我是这么脱的，这些微信包都是托朋友搞的

**Comment by shenzudan** [comment]
> 

打了dylib的 改名 微不信: https://drive.google.com/file/d/1QiVt_mo3DQkJY6dGkBGBCrPdasO-W9ip/view?usp=sharing

**Comment by zwjtano** [comment]
> > > > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > > > 
> > > > 
> > > > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> > > 
> > > 
> > > https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以
> > 
> > 
> > 大佬方便帮忙把这个ipa脱壳改包名让altstore能安装吗 https://www.123pan.com/s/DuLA-ZOUaA 提取码:gwyI
> 
> 打了dylib的 改名 微不信: https://drive.google.com/file/d/1QiVt_mo3DQkJY6dGkBGBCrPdasO-W9ip/view?usp=sharing
> 
> @zwjtano

谢谢大佬 ，带插件的也可以分享一下吗

**Comment by zwjtano** [comment]
> > > > > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > > > > 
> > > > > 
> > > > > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> > > > 
> > > > 
> > > > https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以
> > > 
> > > 
> > > 大佬方便帮忙把这个ipa脱壳改包名让altstore能安装吗 https://www.123pan.com/s/DuLA-ZOUaA 提取码:gwyI
> > 
> > 
> > 打了dylib的 改名 微不信: https://drive.google.com/file/d/1QiVt_mo3DQkJY6dGkBGBCrPdasO-W9ip/view?usp=sharing
> > @zwjtano
> 
> 谢谢大佬 ，带插件的也可以分享一下吗

altstore安装显示 the name of the app is invalid

**Comment by shenzudan** [comment]
> > > > > > > 谷歌盘 脱壳原版: https://drive.google.com/file/d/1h8028F_WVBuyDyamTzr4UtCqTBa24CDM/view?usp=sharing dk插件: https://drive.google.com/file/d/1hqQEAVhcz98M6DTBGBEOi9mVYaAMWi0w/view?usp=sharing
> > > > > > 
> > > > > > 
> > > > > > altStore 安装脱壳原版安装不了，大佬可以帮忙测试一下吗？
> > > > > 
> > > > > 
> > > > > https://drive.google.com/file/d/1z2AWiq0Xq87WUYZEP986WqbXhDjNqvlK/view?usp=sharing 试试这个，我改了包名重签的，在ipad上装了可以
> > > > 
> > > > 
> > > > 大佬方便帮忙把这个ipa脱壳改包名让altstore能安装吗 https://www.123pan.com/s/DuLA-ZOUaA 提取码:gwyI
> > > 
> > > 
> > > 打了dylib的 改名 微不信: https://drive.google.com/file/d/1QiVt_mo3DQkJY6dGkBGBCrPdasO-W9ip/view?usp=sharing
> > > @zwjtano
> > 
> > 
> > 谢谢大佬 ，带插件的也可以分享一下吗
> 
> altstore安装显示 the name of the app is invalid

楼上有各种版本 也有解决办法 自己试试吧

**Comment by monsterszw** [comment]
通过iOS App Signer改App Display Name为英文即可

**Comment by shenbei** [comment]
你们能收到推送么？推送是不是有问题？

**Comment by daqueque** [comment]
> 你们能收到推送么？推送是不是有问题？

偶尔能收到，几率很小。不知道是什么原因。 @shenzudan

**Comment by shenzudan** [comment]
> > 你们能收到推送么？推送是不是有问题？
> 
> 偶尔能收到，几率很小。不知道是什么原因。 @shenzudan

可以研究下APN机制，应该是跟包名还是推送证书之类的有关系吧，毕竟不是原版包，我也不懂

**Comment by daqueque** [comment]
> 大佬，能给一个改名的微信原版ipa吗

上面不是有链接吗

**Comment by ericcug** [comment]
> 你们能收到推送么？推送是不是有问题？

除了后台播放空白声音，是不可能收到推送的，APNS的devicetoken与服务器推送证书有关，不是同一个team签的app是无法通过服务器校验的，会提示bad devicetoken。

**Comment by Stonestonestone** [comment]
感谢大佬，原来闪退现在好使了。

**Comment by Leungwn** [comment]
出来8.0.30后不知道为什么我用大佬的包还是会闪退16.0.3的系统

**Comment by daqueque** [comment]
> 出来8.0.30后不知道为什么我用大佬的包还是会闪退16.0.3的系统

我用的原版脱壳，一直正常使用。

**Comment by Dzy-yubai** [comment]
微不信这个版本在ios16.0.2无法显示微信小助手

**Comment by no1434** [comment]
谢谢大佬！

**Comment by cy920820** [comment]
@shenzudan 大佬，抢红包的功能保留了么？

**Comment by szezhunkin** [comment]
大佬 ios16.1 8.0.29版本出现闪退 求解决方法

**Comment by szezhunkin** [comment]
大佬 ios16.1 8.0.29版本出现闪退（带插件的） 求解决方法

**Comment by DKJone** [comment]
已更新 8.0.38

**Comment by Raven-Cn** [comment]
> 已更新 8.0.38

大佬，我现在是 8.0.29 怎么覆盖升级？

**Comment by DKJone** [comment]
> 

之前什么方式安装的啊，
* 越狱的直接从源更新1.1.0插件，
* 安装包签名的用你之前签名的证书签新包安装，
* xcode安装的直接替换ipa运行安装

**Comment by Raven-Cn** [comment]
> * 书签新包安

我是原版砸壳，altsotre安装的。命名是wechat，是不是新版本也要命名一样了？
