### ISSUE TITLE
xs 拦截撤回消息必崩

### ISSUE THREAD

**Issue by MichaelJokAr** [DKJone/DKWechatHelper#12]
xs 拦截撤回消息必崩

**Comment by uniqueque** [comment]
x也是。。。

**Comment by liupcoder** [comment]
X没崩啊，11.4.1

**Comment by uniqueque** [comment]
> X没崩啊，11.4.1

我是12.2 崩了。还有xr，xr一开始不会蹦，退出重新登录 进来就蹦

**Comment by liupcoder** [comment]
虽然没崩，又被封号了😤心累

uniqueque <notifications@github.com>于2019年4月16日 周二下午4:03写道：
