### ISSUE TITLE
wechat8.0.37脱壳后运行报错

### ISSUE THREAD

**Issue by Gerry1218** [DKJone/DKWechatHelper#127]
Class ThreadQueue is implemented in both /private/var/containers/Bundle/Application/FF0E8FF0-E812-4D0F-A536-636D8433107B/dkhelper.app/Frameworks/ilink_network.framework/ilink_network (0x117ee3a58) and /private/var/containers/Bundle/Application/FF0E8FF0-E812-4D0F-A536-636D8433107B/dkhelper.app/WeChat (0x1151a7db0). One of the two will be used. Which one is undefined.

**Comment by DKJone** [comment]
已更新 8.0.38
