### ISSUE TITLE
7.0.0 的手机安装后，微信设置界面没有微信小助手

### ISSUE THREAD

**Issue by 734566743** [DKJone/DKWechatHelper#14]

**Comment by 734566743** [comment]
微信版本号7.0.0  。项目直接运行在手机上

**Comment by DKJone** [comment]
如果没有改新项目配置，安装之前需要删除原版微信

**Comment by 734566743** [comment]
删除原版微信，再安装 ，现在新版本是  7.0.3 的可以使用吗？。。我刚卸载重装了。也没看到小助手

**Comment by 734566743** [comment]
现在版本变成 7.0.3了。项目啥都没动，就改了证书

**Comment by DKJone** [comment]
可以说一下IOS系统版本和手机型号吗？

**Comment by 734566743** [comment]
手机系统版本:11.4    手机型号:iphoneX
手机系统版本:9.2.1   手机型号:iphone6s

**Comment by 734566743** [comment]
方便加下微信嘛。

**Comment by DKJone** [comment]
1136165636
