### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by ddviper** [DKJone/DKWechatHelper#16]
/Users/DcMac/Library/Developer/Xcode/DerivedData/dkhelper-gnsaaamusjuymfdwysrcfqsnfylt/Build/Intermediates.noindex/dkhelper.build/Debug-iphoneos/dkhelperDylib.build/Script-114CCC3321F817D500A4646E.sh: line 2: /opt/MonkeyDev/bin/md: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
<img width="1134" alt="屏幕快照 2019-03-14 17 07 15" src="https://user-images.githubusercontent.com/7856366/54344365-a4b8b180-467b-11e9-9b8b-647b0cc5b4cd.png">

**Comment by ddviper** [comment]
<img width="1134" alt="屏幕快照 2019-03-14 17 07 15" src="https://user-images.githubusercontent.com/7856366/54344418-c5810700-467b-11e9-8261-ca83bb7cc0e3.png">

**Comment by ddviper** [comment]
<img width="1134" alt="屏幕快照 2019-03-14 17 07 15" src="https://user-images.githubusercontent.com/7856366/54344502-f7926900-467b-11e9-8d4e-237fa507d96f.png">

**Comment by yuhuazhu** [comment]
同遇到这个问题，怎么解决的呀

**Comment by yuhuazhu** [comment]
试着安装了下MonkeyDev，就编译成功了
