### ISSUE TITLE
Xcode编译报错

### ISSUE THREAD

**Issue by Guwudao** [DKJone/DKWechatHelper#18]
library not found for -lcycript
找不到cycript这个库

<img width="821" alt="issue" src="https://user-images.githubusercontent.com/23578651/60269853-d5b6ac80-9921-11e9-8d8c-4a7eb00c8063.png">

ps：我已经安装monkeyDev使用了很久了，应该默认开启了cycript才对，有劳解答

**Comment by DKJone** [comment]
看下 monkeyDev 的framework里有没有cycript默认是安装在`⁩/⁨opt⁩/MonkeyDev⁩/⁨Frameworks⁩`里，没有，就更新下monkeydev,或者找到你自己monkeydev安装路径下面的framework文件夹，加到这里
![image](https://user-images.githubusercontent.com/15855089/60310617-54453580-9986-11e9-9398-1c7ec4e00461.png)

**Comment by Guwudao** [comment]
更新monkeydev已解决，O(∩_∩)O谢谢

**Comment by xiaolanchou** [comment]
编译报错 
![image](https://user-images.githubusercontent.com/8498383/63141697-42445280-c019-11e9-9cf1-dbeaa39d8181.png)

**Comment by imrry** [comment]
> 编译报错
> ![image](https://user-images.githubusercontent.com/8498383/63141697-42445280-c019-11e9-9cf1-dbeaa39d8181.png)

我也是报这个错，你解决了么？

**Comment by DKJone** [comment]
> > 编译报错
> > ![image](https://user-images.githubusercontent.com/8498383/63141697-42445280-c019-11e9-9cf1-dbeaa39d8181.png)
> 
> 我也是报这个错，你解决了么？

安装monkeydev

**Comment by DKJone** [comment]
> 编译报错
> ![image](https://user-images.githubusercontent.com/8498383/63141697-42445280-c019-11e9-9cf1-dbeaa39d8181.png)

同#16
