### ISSUE TITLE
无法请作者喝杯咖啡，闪退

### ISSUE THREAD

**Issue by czl0325** [DKJone/DKWechatHelper#25]
微信->设置->微信小助手->
点击请作者喝杯咖啡，闪退

测试机器：iphone8,ipadmini4,
微信版本：关于微信版本显示7.0.8，但是我从github百度网盘下的是7.0.10的链接。不知道为啥？

**Comment by DKJone** [comment]
已经更新到微信7.0.11，闪退已修复。
