### ISSUE TITLE
微信callkit有吗

### ISSUE THREAD

**Issue by wangzongqi1001** [DKJone/DKWechatHelper#26]
请问微信callkit插件的原理是什么 我的11已经越狱，如何不装插件像替换提示音一样改本地文件来实现callkit

**Comment by DKJone** [comment]
已经新增了CallKit，实现CallKit需要Hook执行程序的方法返回值，替换文件无法实现，不想装插件可以用flex

**Comment by niuzai-png** [comment]
微信CallKit通过flex如何实现开启功能
