### ISSUE TITLE
Cydia Impactor安装未签名版时报错

### ISSUE THREAD

**Issue by tm-zhang** [DKJone/DKWechatHelper#27]
大佬好，我现在在用最新版Cydia Impactor向我的ios 13.5.1 iphone 7安装未签名版7.0.13，但是报error 71:  _assert(!teams.empty())。我翻了各种论坛并尝试了删除原版微信等但依然未解决，请问有建议吗？

**Comment by DKJone** [comment]
`teams.empty()`说明你Them是空的，
<img width="455" alt="1" src="https://user-images.githubusercontent.com/15855089/86194327-cb586f80-bb80-11ea-9726-77657aa09fbc.png">

**Comment by tm-zhang** [comment]
@DKJone 我去xcode 12建了team，这个问题现在解决了，感谢。不过又遇到了新的问题(捂脸)，Cydia Impactor要求我升级至xcode 7.3以上，网上说苹果升级了对开发者账户的要求所以要等原作者解决。然后我换了ios app signer自己签名后用apple configurator 2往我的iphone安，但是依然安装失败并且不知道原因...

**Comment by DKJone** [comment]
安装失败说明签名失败了，你可以在开发者网站上生成配置文件 Profile然后拖到IOS APP signer里，开发者账号需要更新协议，你可以到https://developer.apple.com/account上查看方法,原文
>Verify your identity and review the updated license agreement.
>In order to access certain membership resources, you must accept the latest Apple Developer Program License Agreement agreement by July 6, 2020. Before reviewing, you’ll need to verify your identity using the Apple Developer app on your iPhone or iPad. Open the Apple Developer app, tap the Account tab, sign in with the Apple ID associated with your Apple Developer account, and follow the prompts. Once verification is complete, return to your account on the web.
就是让你下载Apple Developer app然后在账户里完成注册。
