### ISSUE TITLE
修改了bundle identifier还是提示重复，只有把原版微信卸载了才能装，还有就是提示WatchKit相关问题不知道咋弄

### ISSUE THREAD

**Issue by ijoery** [DKJone/DKWechatHelper#31]
Details

Unable to install "dkhelper"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652994
--
This application’s application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652994
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE80000BE)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012164193f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000121680124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000102884b43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012167fe65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x00000001214f0d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x00000001029b32aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x00000001029b4ecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff202b351d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff202b4707 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202ba53e _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff202bb00b _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff202c4b9d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff2045c4e2 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff2045b4b3 start_wqthread + 15
);
}
--

System Information

macOS Version 11.0 (Build 20A5384c)
Xcode 12.0.1 (17220)

--------------------------------

Details

Unable to install "dkhelper"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652971
--
The WatchKit app's Info.plist must have a WKCompanionAppBundleIdentifier key set to the bundle identifier of the companion app.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652971
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE80000D5)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012164193f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000121680124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000102884b43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000012167fe65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x00000001214f0d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x00000001029b32aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x00000001029b4ecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff202b351d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff202b4707 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff202ba53e _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff202bb00b _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff202c4b9d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff2045c4e2 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff2045b4b3 start_wqthread + 15
);
}
--

System Information

macOS Version 11.0 (Build 20A5384c)
Xcode 12.0.1 (17220)

**Comment by DKJone** [comment]
参考 #13

**Comment by ijoery** [comment]
> 参考 #13

好的，感谢

**Comment by ijoery** [comment]
@DKJone 还遗留这个问题，你看怎么解决呢？

Details

Unable to install "dkhelper"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652971
--
The WatchKit app's Info.plist must have a WKCompanionAppBundleIdentifier key set to the bundle identifier of the companion app.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402652971

**Comment by DKJone** [comment]
monkeydev 默认的pack.sh里是会自动删除watchKit内容的，看一下你的脚本是不是安装位置不对，你可以在项目的build Phases 里设置脚本路径，默认是`/opt/MonkeyDev/Tools/pack.sh`,脚本里的52-56行就是删除watchkit内容的
```sh
	# remove Plugin an Watch
	rm -rf "${TARGET_APP_PATH}/PlugIns" || true
	rm -rf "${TARGET_APP_PATH}/Watch" || true

	/usr/libexec/PlistBuddy -c 'Delete UISupportedDevices' "${TARGET_APP_PATH}/Info.plist" 2>/dev/null
```
你也可以自己手动删除源IPA文件里的这部分内容，重新压缩后缀改为IPA，然后将`TargetApp`里的内容删除，放入删除watchkit后的IPA文件重新运行

**Comment by echo-cool** [comment]
> monkeydev 默认的pack.sh里是会自动删除watchKit内容的，看一下你的脚本是不是安装位置不对，你可以在项目的build Phases 里设置脚本路径，默认是`/opt/MonkeyDev/Tools/pack.sh`,脚本里的52-56行就是删除watchkit内容的
> 
> ```shell
> 	# remove Plugin an Watch
> 	rm -rf "${TARGET_APP_PATH}/PlugIns" || true
> 	rm -rf "${TARGET_APP_PATH}/Watch" || true
> 
> 	/usr/libexec/PlistBuddy -c 'Delete UISupportedDevices' "${TARGET_APP_PATH}/Info.plist" 2>/dev/null
> ```
> 
> 你也可以自己手动删除源IPA文件里的这部分内容，重新压缩后缀改为IPA，然后将`TargetApp`里的内容删除，放入删除watchkit后的IPA文件重新运行

已经删除watchkit的内容，但是这个问题还是会继续出现

**Comment by yangsunyue** [comment]
> > monkeydev 默认的pack.sh里是会自动删除watchKit内容的，看一下你的脚本是不是安装位置不对，你可以在项目的build Phases 里设置脚本路径，默认是`/opt/MonkeyDev/Tools/pack.sh`,脚本里的52-56行就是删除watchkit内容的
> > ```shell
> > 	# remove Plugin an Watch
> > 	rm -rf "${TARGET_APP_PATH}/PlugIns" || true
> > 	rm -rf "${TARGET_APP_PATH}/Watch" || true
> > 
> > 	/usr/libexec/PlistBuddy -c 'Delete UISupportedDevices' "${TARGET_APP_PATH}/Info.plist" 2>/dev/null
> > ```
> > 
> > 
> > 你也可以自己手动删除源IPA文件里的这部分内容，重新压缩后缀改为IPA，然后将`TargetApp`里的内容删除，放入删除watchkit后的IPA文件重新运行
> 
> 已经删除watchkit的内容，但是这个问题还是会继续出现

我也是这样的。头疼。

**Comment by zd140623** [comment]
> > > monkeydev 默认的pack.sh里是会自动删除watchKit内容的，看一下你的脚本是不是安装位置不对，你可以在项目的build Phases 里设置脚本路径，默认是`/opt/MonkeyDev/Tools/pack.sh`,脚本里的52-56行就是删除watchkit内容的
> > > ```shell
> > > 	# remove Plugin an Watch
> > > 	rm -rf "${TARGET_APP_PATH}/PlugIns" || true
> > > 	rm -rf "${TARGET_APP_PATH}/Watch" || true
> > > 
> > > 	/usr/libexec/PlistBuddy -c 'Delete UISupportedDevices' "${TARGET_APP_PATH}/Info.plist" 2>/dev/null
> > > ```
> > > 
> > > 
> > > 你也可以自己手动删除源IPA文件里的这部分内容，重新压缩后缀改为IPA，然后将`TargetApp`里的内容删除，放入删除watchkit后的IPA文件重新运行
> > 
> > 
> > 已经删除watchkit的内容，但是这个问题还是会继续出现
> 
> 我也是这样的。头疼。

在删除PlugIns和Watch文件的代码后加上如下代码即可
rm -rf "${TARGET_APP_PATH}/com.apple.WatchPlaceholder" || true

**Comment by ceeyang** [comment]
@zd140623  楼上完美解决问题。
