### ISSUE TITLE
xcode 打包真机运行后无法收到微信推送

### ISSUE THREAD

**Issue by koolss** [DKJone/DKWechatHelper#32]
![image](https://user-images.githubusercontent.com/45249733/96095413-23816a80-0f01-11eb-9592-959d77e9d594.png)
![image](https://user-images.githubusercontent.com/45249733/96095524-49a70a80-0f01-11eb-8470-4bf8ca0aa07c.png)

**Comment by DKJone** [comment]
#11

**Comment by koolss** [comment]
> [＃11](https://github.com/DKJone/DKWechatHelper/issues/11)

博主 是这样的 dkhelper 和 dkhelperDylib 两个模块 bundle identifier都是使用的com.tencent.xin   团队账号我使用企业版的签名打包，我并未杀死进程，微信最小化于后台还是无法收到微信通知，不知是否我哪儿操作没有对？请教一哈。
