### ISSUE TITLE
安装 8.0.1失败

### ISSUE THREAD

**Issue by daqueque** [DKJone/DKWechatHelper#41]
未越狱用户下载的未签名版本8.0.1版本，使用爱思助手安装失败。手机本身安装的有一个微信。
提示：安装包验证失败或设备未越狱

是否因为手机本身安装了一个微信，两个都叫微信冲突了？怎么修改名字了？或者不是这个原因。

**Comment by DKJone** [comment]
用爱思重签名安装

**Comment by shenzudan** [comment]
![image](https://user-images.githubusercontent.com/17032816/106383646-26e22880-6402-11eb-8a28-daab1e10e2d8.png)
我改了包名重新签名安装提示这个

**Comment by zqjimlove** [comment]
看 #30
