### ISSUE TITLE
ios版本7.0.15已越狱  点击卡住，退出后在进来就消失了

### ISSUE THREAD

**Issue by YUJANLKS** [DKJone/DKWechatHelper#43]
iphoneXS微信版本7.0.15，cydia安装好后到设置能看到插件，点击后卡住，划掉后台在进入微信插件就不见了，插件还是已安装状态。没有安装其他红包插件，请问是什么问题？

**Comment by DKJone** [comment]
安装对应版本的
v1.0.7适用微信8.0.1
v1.0.6适用微信7.0.17
v1.0.5适用微信7.0.15
v1.0.4适用微信7.0.14
