### ISSUE TITLE
8.0.1CallKit无法正常使用

### ISSUE THREAD

**Issue by zjy369** [DKJone/DKWechatHelper#48]
锁屏后，收到微信语音，没有任何提示，包括原来的通知栏。关闭CallKit后也无法显示语音栏

现在只有停留在app界面能收到语音提示，或者切到桌面后，立马打过来有效

开了后台刷新权限

**Comment by DKJone** [comment]
没有越狱，微信没有后台运行的权限，你可以打开后台抢红包的开关试试

**Comment by zjy369** [comment]
好的，感谢
