### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by LeslieZhang** [DKJone/DKWechatHelper#51]
使用pp助手和爱思助手，安装8.0.1版的无签名。删除了com.apple.WatchPlaceholder。压缩改名ipa，之后安装失败

**Comment by DKJone** [comment]
先重签名

**Comment by lulujyc** [comment]
可以使用这个修改好的ipa：

链接: https://pan.baidu.com/s/1lp1qjjrvlOa_Tzb7APyhiQ 提取码: w6bm 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by kxinds** [comment]
> 可以使用这个修改好的ipa：
> 
> 链接: https://pan.baidu.com/s/1lp1qjjrvlOa_Tzb7APyhiQ 提取码: w6bm 复制这段内容后打开百度网盘手机App，操作更方便哦

这个ipa也安装失败了哦，需要重签名吧

**Comment by lulujyc** [comment]
> > 可以使用这个修改好的ipa：
> > 链接: https://pan.baidu.com/s/1lp1qjjrvlOa_Tzb7APyhiQ 提取码: w6bm 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 这个ipa也安装失败了哦，需要重签名吧

用altstore

**Comment by hyy1233** [comment]
越狱插件的地址打不开了，这源码咋改成deb插件？
