### ISSUE TITLE
deb插件更新下，deb插件还是103版本

### ISSUE THREAD

**Issue by hyy1233** [DKJone/DKWechatHelper#56]
deb插件更新下

**Comment by DKJone** [comment]
添加源`https://dkjone.github.io/`下载
deb文件地址[https://github.com/DKJone/dkjone.github.io/tree/master/debs](https://github.com/DKJone/dkjone.github.io/tree/master/debs)

**Comment by hyy1233** [comment]
能上次个百度云或者蓝奏云嘛，这个github网址我这都打不开



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月2日(星期二) 中午1:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DKJone/DKWechatHelper] deb插件更新下，deb插件还是103版本 (#56)




 
添加源https://dkjone.github.io/下载
 deb文件地址https://github.com/DKJone/dkjone.github.io/tree/master/debs

**Comment by DKJone** [comment]
[debs](https://gitee.com/DKJone/dkjone.github.io/tree/master/debs)
