### ISSUE TITLE
图片等资源找不到

### ISSUE THREAD

**Issue by 546200350** [DKJone/DKWechatHelper#59]
![image](https://user-images.githubusercontent.com/16091917/111874301-94a4dc80-89cf-11eb-9755-dbf42437d586.png)
请教下这个怎么处理

**Comment by DKJone** [comment]
文件夹路径改一下，指向这个文件夹 `DKWechatHelper/dkhelper/dkhelperDylib/vapFiles/`

**Comment by 546200350** [comment]
能麻烦具体说一下再哪儿改么？？ 非专业iOS开发
我现在都是去launchDemo下拷贝了一份vapFiles文件夹

**Comment by DKJone** [comment]
更新 已提交。
