### ISSUE TITLE
传包的时候出现这个错误？ 请问大佬知道怎么处理么？

### ISSUE THREAD

**Issue by 546200350** [DKJone/DKWechatHelper#60]
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'wechatfamily.app/WeChat' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

**Comment by DKJone** [comment]
非IOS开发不推荐你直接使用项目。配置好monkeydev和需要的库文件真机运行。

**Comment by 546200350** [comment]
我也试过用monkeydev,也是这个问题，，可以帮忙解决吗大佬？  有偿  wx: KaKaysVip
