### ISSUE TITLE
ld: file not found: /usr/lib/libstdc++.dylib

### ISSUE THREAD

**Issue by yangsunyue** [DKJone/DKWechatHelper#63]
运行报错，MonkeyDev是安装了的。

**Comment by DKJone** [comment]
安装C++库
https://github.com/devdawei/libstdc-

**Comment by yangsunyue** [comment]
好的已解决。谢谢~

**Comment by yangsunyue** [comment]
我重签上传App Store一堆报错。是动态库的问题吗。还是什么别的问题？

ERROR ITMS-90047: "Disallowed paths ( "SC_Info" ) found at: Payload/dkhelper.app."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'dkhelper.app/TargetApp' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'dkhelper.app/Frameworks/libstdc++.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'dkhelper.app/WeChat' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

**Comment by yangsunyue** [comment]
我重签上传App Store一堆报错。是动态库的问题吗。还是什么别的问题？

ERROR ITMS-90047: "Disallowed paths ( "SC_Info" ) found at: Payload/dkhelper.app."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'dkhelper.app/TargetApp' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'dkhelper.app/Frameworks/libstdc++.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'dkhelper.app/WeChat' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

**Comment by yangsunyue** [comment]
感谢大佬
