### ISSUE TITLE
关于T出当前设备登陆,启用动态启动图会卡死界面，无法登陆（已解决，望更新代码）

### ISSUE THREAD

**Issue by HOOKDLL** [DKJone/DKWechatHelper#65]
“动态启动图” 选项启动后，如果当前帐号被其它设备登陆，T出当前设备登陆（这种情况比较少）但遇见不得不重装APP，运行完动态图效果后会卡死界面，永远无法登陆，希望更新修复下。

我经过调试得知

原因：
代码中用到UIWindow *window = [UIApplication sharedApplication].keyWindow 统一修改成UIWindow *window = [UIApplication sharedApplication].delegate.window，会被uiactionsheet影响，只要任何一个地方弹过actionsheet, 页面就死掉不能操作了

```
-(void)goNextVC{
    UIWindow *window = UIApplication.sharedApplication.keyWindow;
    window.rootViewController = nil;
    [UIApplication.sharedApplication.keyWindow setHidden:true];
    //[UIApplication.sharedApplication.delegate.window makeKeyAndVisible];//这行卡死
    [UIApplication.sharedApplication.keyWindow makeKeyAndVisible];//修正代码
}
```

希望修复。

**Comment by DKJone** [comment]
已采纳！#66
