### ISSUE TITLE
IOS 15不支持了

### ISSUE THREAD

**Issue by haifengzuishuai** [DKJone/DKWechatHelper#77]
![b8a5588db3877b0d1e0118d57fea8ea](https://user-images.githubusercontent.com/46316222/134270336-74254b5e-f2b0-490a-a553-b0fd7052000e.jpg)

**Comment by dogegg-cc** [comment]
签名证书问题，需要用新版xcode，重新签名

**Comment by cy920820** [comment]
大佬重现了，更细一下吧 @DKJone

**Comment by DKJone** [comment]
> 大佬重现了，更细一下吧 @DKJone

已经更新了。
