### ISSUE TITLE
大佬你好，使用altStore安装包错 The name for this app is invalid ，请问可以如何解决

### ISSUE THREAD

**Issue by seepine** [DKJone/DKWechatHelper#87]

**Comment by DKJone** [comment]
AltStore bug 文件名或者APP名称里包含中文，
参考[altStore issues 154](https://github.com/rileytestut/AltStore/issues/154)

**Comment by seepine** [comment]
感谢大佬，我在info.plist中将`Bundle display name`原来的`微信`改成` WeChat2`，可以安装上了，不过好奇它桌面显示名字还是`微信`..

**Comment by DKJone** [comment]
应该是info.plist 国际化了字符串存在别处，你只改了默认的，实际显示的在`zh_CN.lproj`里的`InfoPlist.strings`

**Comment by seepine** [comment]
晓得了的确看到了`CFBundleDisplayName`是`微信`，再请假一下大佬，现在alt安装会覆盖原来的，如果要安装多个微信，应该修改哪里呢，然后能不能修改LOGO图

**Comment by DKJone** [comment]
改 CFBundleIdentifier 试试
