### ISSUE TITLE
安装成功后，打开后黑屏

### ISSUE THREAD

**Issue by Bigbear-Smallbear** [DKJone/DKWechatHelper#88]
项目版本1.0.9，安装包为8.0.13未签名版ipa，运行后成功安装在手机上，但是打开应用后黑屏。
（使用项目1.0.7运行安装正常）

**Comment by DKJone** [comment]
由于微信新版本使用 SceneDelegate替代APPdelegate导致的，不同版本配置了不同启动页。
解决方法：替换项目目录下`info.plist`为安装包里的 `info.plist`。或者删除`info.plist`后关闭xcode重新打开，编译时会自动去ipa文件里找`info.plist`并拷贝出来。
