### ISSUE TITLE
使用altstore安装的时候提示The name for this app is invalid，请问怎么解决？

### ISSUE THREAD

**Issue by XianYuDaXian** [DKJone/DKWechatHelper#90]
![3605D57F54D5AFCBE14D6F6AB0FC8105](https://user-images.githubusercontent.com/20138259/149521194-773a982e-8c9a-45b7-b18f-99568f8ec374.png)
搜索过其他方法，比如修改info.plist里的string，但是不起作用

**Comment by XianYuDaXian** [comment]
感谢回复，按照你给的issues修改了CFBundleDisplayName后，得到和我参照网络搜索的修改info.plist一样的结果，依然安装失败。
![QQ图片20220114213758](https://user-images.githubusercontent.com/20138259/149524261-2e801555-1393-4137-884c-d144de50e503.png)
![_20223514093543](https://user-images.githubusercontent.com/20138259/149524275-9803ae82-5985-4738-bd67-97c52d7454d9.png)

**Comment by DKJone** [comment]
如果安装包里有watchplaceholder文件夹可以删除watchplaceholder文件夹重签

**Comment by XianYuDaXian** [comment]
最后我使用Sideloadly成功安装上了，还是非常感谢

**Comment by BreezeFp** [comment]
我用爱思助手安装的，感觉比altserver方便
